---
deployment:
  tasks:
    - export DEPLOYPATH=/home/s28sheoe5xht/public_html/newsico
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
